message: 'It would be nice that someone in customrealms/cli would add configs argument in package.json like: 
        "name": "example-plugin",
        "version": "1.0.0",
        "description": "",
        "configs: { 
          "config": "./configs/config.yml", 
          "messages": "./configs/messages.yml", 
          "data": "./configs/data.yml" 
        }
        couse now if u try to save custom plugin it will crash, because there is no corresponding config file in resources'