name: OpenRealms
api-version: 1.13
version: 1.0.0
main: io.projopenrealms.MainPlugin

libraries:
  - org.jetbrains:annotations:26.0.2
  - org.graalvm.js:js-language:24.2.2
  - org.graalvm.truffle:truffle-runtime:24.2.2