on: [pull_request]

name: Pull Request Checks

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the Maven Project
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk

      - name: Build Maven project
        run: mvn package
