on:
  release:
    types: [created]

name: Release

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the Maven Project
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Release Details
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk

      - name: Build Maven project
        run: mvn package

      - name: Upload Maven build output
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/bukkit-runtime.jar
          asset_name: bukkit-runtime.jar
          asset_content_type: application/octet-stream

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Update version in package.json
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('src/typescript/package.json', 'utf8'));
            packageJson.version = '${{ github.event.release.tag_name }}'.replace(/^v/, '');
            fs.writeFileSync('src/typescript/package.json', JSON.stringify(packageJson, null, 2));

      - name: Publish to npm
        working-directory: src/typescript
        run: npm publish
