on:
  release:
    types: [created]

name: Build JAR files

jobs:
  build:
    strategy:
      matrix:
        mc: [1.16.4, 1.17.1, 1.20.6]

    runs-on: ubuntu-latest
    name: Build the Maven Project
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Release Details
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      -
        name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk
      -
        name: Build Maven project
        working-directory: .
        run: mvn package -PMC_${{ matrix.mc }}
      -
        name: Upload Maven build output
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./target/bukkit-runtime-jar-with-dependencies.jar
          asset_name: bukkit-runtime-${{ matrix.mc }}.jar
          asset_content_type: application/octet-stream
